import mongoose, { Document, Model, Schema } from "mongoose";

export interface IParticipant {
  id: string; // The UUID or custom string generated by frontend or backend
  name: string;
  hasSubmitted: boolean;
  isJoined?: boolean;
}

export interface IGDGroup extends Document {
  groupId: string; // Unique string (like A7X9Q or full uuid)
  topic: string;
  date?: string;
  time?: string;
  duration?: string;
  status: "open" | "closed";
  participants: IParticipant[];
  createdAt: Date;
}

const ParticipantSchema = new Schema<IParticipant>({
  id: { type: String, required: true },
  name: { type: String, required: true },
  hasSubmitted: { type: Boolean, default: false },
  isJoined: { type: Boolean, default: false },
}, { _id: false }); // Disable automatic _id for nested subdocuments unless needed

const GDGroupSchema = new Schema<IGDGroup>(
  {
    groupId: { type: String, required: true, unique: true, index: true },
    topic: { type: String, required: true },
    date: { type: String },
    time: { type: String },
    duration: { type: String },
    status: { type: String, enum: ["open", "closed"], default: "open" },
    participants: { type: [ParticipantSchema], default: [] },
    createdAt: { type: Date, default: Date.now },
  },
  { timestamps: true }
);

export const GDGroup: Model<IGDGroup> =
  mongoose.models.GDGroup || mongoose.model<IGDGroup>("GDGroup", GDGroupSchema);
